version: "3"


services:
  yocto_project:
    container_name: yocto_project
    image: yocto-image
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID
        - GID
    volumes:
      - ./assembly:/home/yocto_user/project/assembly

