
services:
  yocto-container:
    container_name: yocto-container
    image: yocto-image
    # stdin_open: true
    tty: true
    build:
      context: ../
      dockerfile: ./yocto-build/Dockerfile
      target: base
      args:
        - CODENAME
        - CORE
        - REQS_ARG
        - UID=1000
        - GID=1000
        - LANG=en_US.UTF-8
        - LC_ALL=en_US.UTF-8
        - YOCTO_INSTALL_PATH=/home/yocto_user/project
    environment:
      - ASSEMBLY_DIR=/home/yocto_user/project/assembly
      - SCRIPTS_DIR=/home/yocto_user/project/assembly/scripts
      - POKY_DIR=/home/yocto_user/project/assembly/poky
      - PATCHES_DIR=/home/yocto_user/project/yocto-patches
      - STAGE_VAR
      - YOCTO_COMMIT_HASH=7733ddf733b883d6fe75768d5f9b6d3519d47dc3
      - BRANCH_NAME=my-upstream_5.0.1
      - TRACING_TOOL
      - TRACING_OPTIONS
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    privileged: true
    volumes:
      - ../yocto-patches:/home/yocto_user/project/yocto-patches
      - ./assembly:/home/yocto_user/project/assembly
      - ../conf:/home/yocto_user/project/conf

