version: "3"


services:
  yocto_project:
    container_name: yocto_project
    image: yocto-image
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=1000
        - GID=1000
        - LANG=en_US.UTF-8
        - LC_ALL=en_US.UTF-8
        - YOCTO_INSTALL_PATH=/home/yocto_user/project
    volumes:
      - ./assembly:/home/yocto_user/project/assembly
